Repository JunalChowdhuryG/Grupo-2-Practica-Calificada-3, pull requests merged in 2025-06, with the labels that each got.

#7 feat[#1]: Inicializar repositorio y estructura
  .gitignore
  README.md
  issues.json
  pytest.ini
  requirements.txt
  src/__init__.py
  tests/__init__.py
Labels: sprint_1, PR_accept

#8 feat[#2]: Implementar git hook commit-msg
  git/hooks/commit-msg.sh
Labels: sprint_1

#12 merge[#5]: Agregar issues.json con los 5 primeros issues
  issues.json
Labels: sprint_1

#14 merge[#13]: Fusionar rama docs-Readme-Sprint-1 a develop
  README.md
Labels: sprint_1, PR_accept

#20 merge[#17]: Fusionar rama feature-kanban-mejora a develop
  docs/kanban.md
  scripts/generar_kanban.sh
Labels: sprint_2, in_review

#32 merge[#29]: Fusionar rama feature-kanban-optimizado a develop
  docs/kanban.md
  scripts/generar_kanban.sh
Labels: sprint_3, in_review

#35 merge[#27]: Fusionar rama feature-test-notificar a develop
  requirements.txt
  tests/test_notificar_retrasos.py
Labels: sprint_3, in_review
